### ISSUE TITLE
Access Point Mode not working

### ISSUE THREAD

**Issue by supawiz6991** [matt2005/RoadApplePi#5]
Hello!
Device: Rasberry Pi B 3+ rev 1.3
OS: Raspbian lite GNU/Linux 10 (buster)

Issue:
I was able to get Road Apple Pi Installed and was able to access the web portal via my home network. Upon initial install of Raspbian I set the country code for wifi, timezone, etc. After install of RAP, I entered the options for the access point mode in the RAP web portal but the ssid does not show up on my iphone.

Troubleshooting:
I found that doing:
`sudo hostapd /etc/hostapd/hostapd-rap.conf`
would get the ap ssid to show up. There is an error reported though:
wlan0: could not connect to kernel driver
Also, this is not the preferred method of having to get this to work. 

I've also tried reimaged the sdcard and ran setup.sh with sudo but the result is the same. 

Doing `sudo systemctl status hostapd` shows that its masked and dead.

When I go into `sudo raspbi-config` -> localization options -> WLAN country I get the following errors:
Could not communicate with wpa_supplicant.conf
There was an error running option L4 WLAN Country

Some research shows perhaps a wpa_supplicant.conf file may need created and dropped in the boot directory. If this is the case, would you be able to provide an example of a proper wpa_supplicant.conf file for this use case?

If the issue is not the wpa_supplicant.conf file, would you happen to know what the cause of the problem is?

**Comment by mswhin63** [comment]
Seems this project is dead, I have the same issue, but your log is dated back in March with no response. Hopefully, I will try to locate the issue and solve it, I may get back on and update.
